staff/urls.py
from django.conf.urls import patterns, url

from staff.views import contact_us
from staff.views import email_instance
from staff.views import email_list
from staff.views import email_reply
from staff.views import send_email_reply


urlpatterns = patterns('',
    url(r'^contact_us/$', contact_us, name='contact_us'),
    url(r'^email_instance/$', email_instance, name='email_instance'),
    url(r'^email_list/$', email_list, name='email_list'),
    url(r'^email_reply/$', email_reply, name='email_reply'),
    url(r'^send_email_reply/$', send_email_reply, name='send_email_reply')
)

website/urls.py
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^staff/', include('staff.urls', namespace="staff")),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

staff/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

TITLE_CHOICES = (
    (1, _("Head")),
    (2, _("Second")),
    (3, _("Staff")))

class Department(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    chair = models.BooleanField()
    
    def __unicode__(self):
        return self.name    
    
class Position(models.Model):
    user = models.ForeignKey(User)     
    department = models.ForeignKey(Department)     
    title = models.IntegerField(choices=TITLE_CHOICES)
    special_title_name = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return "%s - %s (%s)" % (self.department.name, self.user.get_full_name(), self.get_title_display())    

class ContactUsLog(models.Model):
    from_email = models.EmailField()
    to_department = models.CharField(max_length=100)
    to_email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField()
    sent_successfully = models.BooleanField()
    
    def __unicode__(self):
        return "%s: %s" % (self.to_department, self.subject)
    
class EmailLog(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)
    from_email = models.EmailField()
    to = models.CharField(max_length=255, blank=True, null=True)
    cc = models.CharField(max_length=255, blank=True, null=True)
    department = models.ForeignKey(Department, blank=True, null=True)     
    timestamp = models.DateTimeField()
    sent_successfully = models.BooleanField()

    def __unicode__(self):
        return "%s: %s" % (self.from_email, self.subject)

staff/views.py
import json
import logging

from django.core.mail.message import EmailMessage
from django.http.response import HttpResponse
from django.http.response import HttpResponseForbidden
from django.http.response import HttpResponseNotFound
from django.http.response import HttpResponseServerError
from django.utils import timezone

from staff.models import Department
from staff.models import EmailLog
from staff.models import Position
from website import settings


logger = logging.getLogger(__name__)

def contact_us(request):
    # Save this email in the database.
    emailLog = EmailLog()
    emailLog.subject = request.POST.get('subject')
    emailLog.body = request.POST.get('message')
    emailLog.from_email = request.POST.get('from_email')
    to_department_id = request.POST.get('to_department')
    to_department = Department.objects.get(pk=to_department_id)
    emailLog.to = to_department.email
    
    cc = []
    emailLog.cc = None
    cc_departments = Department.objects.filter(chair=True).exclude(id=to_department_id)
    for cc_department in cc_departments:
        cc.append(cc_department.email)
        if emailLog.cc == None:
            emailLog.cc = cc_department.email
        else:
            emailLog.cc += "," + cc_department.email
            
    emailLog.department = to_department     
    emailLog.timestamp = timezone.now()
    emailLog.sent_successfully = False
    emailLog.save()
    
    # Send the message.
    email_message = EmailMessage()
    subject = settings.CONTACT_US_SUBJECT_PREFIX + emailLog.subject
    body = "-------------------------------------------------------------------------------\n"
    body += "    Message sent from %s on %s.\n" % (emailLog.from_email, emailLog.timestamp.strftime("%Y-%m-%d %I:%M %p"))
    body += "    Go to %s?emailId=%s to reply.\n" % (request.build_absolute_uri("/staff-only/email-log/"), emailLog.id)
    body += "-------------------------------------------------------------------------------\n"
    if emailLog.body == None or emailLog.body == "":
        subject = subject + "<eom>"
    else:
        body += emailLog.body
        
    email_message.subject = subject
    email_message.body = body
    email_message.to = [emailLog.to]
    if cc:
        email_message.cc = cc

    try:
        email_message.send()
        emailLog.sent_successfully = True
        emailLog.save()
        return HttpResponse()
    except:
        logger.exception("Error sending email. from_email=" + str(emailLog.from_email) + ", to_department=" + str(emailLog.department) + ", subject=" + str(emailLog.subject))
        return HttpResponseServerError()

def email_instance(request):
    # If the current user is not logged in, access is denied.
    if not request.user.is_authenticated() or not request.user.is_active:
        return HttpResponseForbidden()
    
    # Does this email actually exist?
    emailId = request.GET.get("emailId")
    emailLog = None
    try:
        emailLog = EmailLog.objects.get(pk=emailId)
    except EmailLog.DoesNotExist:
        return HttpResponseNotFound()
    
    # Is the current user con-chair (or vice-chair)? Try to find a position record.
    position = Position.objects.filter(user__id=request.user.id, title__in=[1, 2], department__chair=True)
    # If the user is a super-user or a con-chair, then he can see the email.
    # Otherwise, ...
    if not request.user.is_superuser and not position.exists():
        # ... the email must be for a department that the current user is head or second of.
        position = Position.objects.filter(user__id=request.user.id, title__in=[1, 2], department__id=emailLog.department.id)
        if not position.exists():
            return HttpResponseForbidden()
        
    email = {}
    email["from_email"] = emailLog.from_email
    email["to"] = emailLog.to
    email["cc"] = emailLog.cc
    email["subject"] = emailLog.subject
    email["body"] = emailLog.body
    email["timestamp"] = emailLog.timestamp.strftime("%Y-%m-%d %I:%M %p")
    email["sent_successfully"] = emailLog.sent_successfully
        
    context = {}
    context["email"] = email

    try:
        content = json.dumps(context)
        return HttpResponse(content, content_type='application/json')
    except:
        logger.exception("Error serializing email with id=" + str(emailId))
        return HttpResponseServerError()

def email_list(request):
    # If the current user is not logged in, access is denied.
    if not request.user.is_authenticated() or not request.user.is_active:
        return HttpResponseForbidden()
    
    email_log = []
            
    # Is the current user con-chair (or vice-chair)? Try to find a position record.
    position = Position.objects.filter(user__id=request.user.id, title__in=[1, 2], department__chair=True)
    # If the user is a super-user or a con-chair, show all the emails.
    if request.user.is_superuser or position.exists():
        email_log = EmailLog.objects.order_by("-timestamp")
    else:
        # Otherwise, show just the emails for the departments that the current user is head or second of.
        departmentIds = Position.objects.filter(user__id=request.user.id, title__in=[1, 2]).values('department')
        email_log = EmailLog.objects.filter(department__id__in=departmentIds).order_by("-timestamp")

    emails = []
    for log_entry in email_log:
        email = {}
        email["id"] = log_entry.id
        email["from_email"] = log_entry.from_email
        email["to"] = log_entry.to
        email["subject"] = log_entry.subject
        email["timestamp"] = log_entry.timestamp.strftime("%Y-%m-%d %I:%M %p")
        email["sent_successfully"] = log_entry.sent_successfully
        emails.append(email);

    context = {}
    context["emails"] = emails

    try:
        content = json.dumps(context)
        return HttpResponse(content, content_type='application/json')
    except:
        logger.exception("Error serializing email list.")
        return HttpResponseServerError()

def email_reply(request):
    # If the current user is not logged in, access is denied.
    if not request.user.is_authenticated() or not request.user.is_active:
        return HttpResponseForbidden()

    # Does this email actually exist?
    emailId = request.GET.get("emailId")
    emailLog = None
    try:
        emailLog = EmailLog.objects.get(pk=emailId)
    except EmailLog.DoesNotExist:
        return HttpResponseNotFound()

    # Is the current user con-chair (or vice-chair)? Try to find a position record.
    position = Position.objects.filter(user__id=request.user.id, title__in=[1, 2], department__chair=True)
    # If the user is a super-user or a con-chair, then he can see the email.
    # Otherwise, ...
    if not request.user.is_superuser and not position.exists():
        # ... the email must be for a department that the current user is head or second of.
        position = Position.objects.filter(user__id=request.user.id, title__in=[1, 2], department__id=emailLog.department.id)
        if not position.exists():
            return HttpResponseForbidden()
    reply = {}
    reply["department_id"] = emailLog.department.id
    reply["from_email"] = emailLog.to
    reply["to"] = emailLog.from_email
    reply["cc"] = emailLog.cc
    reply["subject"] = "RE: " + settings.CONTACT_US_SUBJECT_PREFIX + emailLog.subject
    body = "\n"
    body += "\n"
    body += "-------------------------------------------------------------------------------\n"
    body += "    Message sent from %s on %s.\n" % (emailLog.from_email, emailLog.timestamp.strftime("%Y-%m-%d %I:%M %p"))
    body += "-------------------------------------------------------------------------------\n"
    body += emailLog.body
    reply["body"] = body

    context = {}
    context["reply"] = reply

    try:
        content = json.dumps(context)
        return HttpResponse(content, content_type='application/json')
    except:
        logger.exception("Error serializing reply for email with id=" + str(emailId))
        return HttpResponseServerError()
    
def send_email_reply(request):
    # Save this email in the database.
    emailLog = EmailLog()
    emailLog.subject = request.POST.get('reply_subject')
    emailLog.body = request.POST.get('reply_body')
    emailLog.from_email = request.POST.get('reply_from')
    emailLog.to = request.POST.get('reply_to')
    emailLog.cc = request.POST.get('reply_cc')
    reply_department_id = request.POST.get('department_id')
    reply_department = Department.objects.get(pk=reply_department_id)
    emailLog.department = reply_department     
    emailLog.timestamp = timezone.now()
    emailLog.sent_successfully = False
    emailLog.save()
    
    # Send the message.
    email_message = EmailMessage()
    email_message.subject = emailLog.subject
    email_message.body = emailLog.body
    email_message.from_email = emailLog.from_email

    if emailLog.to:
        email_message.to = emailLog.to.split(',')

    if emailLog.cc:
        email_message.cc = emailLog.cc.split(',')

    try:
        email_message.send()
        emailLog.sent_successfully = True
        emailLog.save()
        return HttpResponse()
    except:
        logger.exception("Error sending email. from_email=" + str(emailLog.from_email) + ", to_department=" + str(emailLog.department) + ", subject=" + str(emailLog.subject))
        return HttpResponseServerError()

staff/templates/contact_us.html
{% load cms_tags staticfiles sekizai_tags %}

{% addtoblock "js" %}
    <script>
        $(document).ready(function() {
            // Initialize form.
            clear_contact_us_{{ instance.id }}();
            clear_errors_{{ instance.id }}();
            $("#contact_us_form_{{ instance.id }}").show();
            
            // When the send button is pressed ...
            $("#contact_us_{{ instance.id }}").click(function() {
                if (validate_contact_us_{{ instance.id }}()) {
                    var jqXHR = send_contact_us_{{ instance.id }}();
                    jqXHR.done(function( data, textStatus, jqXHR ) {
                        alert("Thank you for your message.");
                        clear_contact_us_{{ instance.id }}();
                    });
                    jqXHR.fail(function( jqXHR, textStatus, errorThrown ) {
                        $("#error-list_{{ instance.id }}").append("<li>Message was not sent because of internal server error. Please try again later.</li>");
                    });
                }
                return false;
            });
        });

        function clear_contact_us_{{ instance.id }}() {
            $("#from_email_{{ instance.id }}").val("");
            $("#to_department_{{ instance.id }}").val("-1");
            $("#subject_{{ instance.id }}").val("");
            $("#message_{{ instance.id }}").val("");
        }

        function clear_errors_{{ instance.id }}() {
            $("#error-list_{{ instance.id }}").empty();
            $("#from_email_form-group_{{ instance.id }}").removeClass("has-error");
            $("#to_department_form-group_{{ instance.id }}").removeClass("has-error");
            $("#subject_form-group_{{ instance.id }}").removeClass("has-error");
            $("#message_form-group_{{ instance.id }}").removeClass("has-error");
        }

        function validate_contact_us_{{ instance.id }}() {
            // Intialize errors.
            clear_errors_{{ instance.id }}();
            var errors = [];
            
            // Validate from email.
            if ($("#from_email_{{ instance.id }}").val() == "") {
                errors[errors.length] = "From Email may not be blank.";
                $("#from_email_form-group_{{ instance.id }}").addClass("has-error");
            } else if (!isValidEmailAddress($("#from_email_{{ instance.id }}").val())) {
                errors[errors.length] = "From Email must be a valid email address.";
                $("#from_email_form-group_{{ instance.id }}").addClass("has-error");
            }
            
            // Validate to department.
            if ($("#to_department_{{ instance.id }}").val() == "-1") {
                errors[errors.length] = "To Department may not be blank.";
                $("#to_department_form-group_{{ instance.id }}").addClass("has-error");
            }
            
            // Validate subject.
            if ($("#subject_{{ instance.id }}").val() == "") {
                errors[errors.length] = "Subject may not be blank.";
                $("#subject_form-group_{{ instance.id }}").addClass("has-error");
            }
            
            // Validate message.
            if (errors.length == 0 && $("#message_{{ instance.id }}").val() == "") {
                if (!confirm("Send this message with no text?")) {
                    errors[errors.length] = "Message should not be blank.";
                    $("#message_form-group_{{ instance.id }}").addClass("has-error");
                }
            }
            
            // List the errors.
            for (i = 0; i < errors.length; ++i) {
                $("#error-list_{{ instance.id }}").append("<li>" + errors[i] + "</li>");
            }

            return errors.length == 0;
        }
        
        function isValidEmailAddress(emailAddress) {
            var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
            return pattern.test(emailAddress);
        }        
        
        function send_contact_us_{{ instance.id }}() {
            var data = $("#contact_us_form_{{ instance.id }}").serialize();
            var jqXHR = $.ajax({
                type: "POST",
                url: "{% url 'staff:contact_us' %}",
                data: data
            });
            return jqXHR;
        }
    </script>
{% endaddtoblock %}

<ul id="error-list_{{ instance.id }}" class="text-danger"></ul>
<form id="contact_us_form_{{ instance.id }}" onsubmit="return false;" style="display: none;">
    {% csrf_token %}
    <div class="form-group" id="from_email_form-group_{{ instance.id }}">
        <label class="control-label" for="from_email_{{ instance.id }}">From Email</label>
        <input type="text" class="form-control" id="from_email_{{ instance.id }}" name="from_email" placeholder="From Email Address" />
    </div>
    <div class="form-group" id="to_department_form-group_{{ instance.id }}">
        <label class="control-label" for="to_department_{{ instance.id }}">To Department</label>
        <select class="form-control" id="to_department_{{ instance.id }}" name="to_department">
            <option value="-1">Select Department</option>
            {% for department in departments %}
                <option value="{{ department.id }}">{{ department.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group" id="subject_form-group_{{ instance.id }}">
        <label class="control-label" for="subject_{{ instance.id }}">Subject</label>
        <input type="text" class="form-control" id="subject_{{ instance.id }}" name="subject" placeholder="Subject" />
    </div>
    <div class="form-group" id="message_form-group_{{ instance.id }}">
        <label class="control-label" for="message_{{ instance.id }}">Message</label>
        <textarea type="text" class="form-control" id="message_{{ instance.id }}" name="message" rows="5" placeholder="Message"></textarea>
    </div>
    <button id="contact_us_{{ instance.id }}" class="btn btn-primary">Send</button>
</form>

staff/templates/staff_list.html
{% load cms_tags %}

<div class="table-responsive">
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Positions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td><a href="mailto:{{ user.email }}">{{ user.email }}</td>
                    <td>{{ user.positions }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>